import { useEffect, useMemo, useState } from 'react';
import { Modal } from '../../components/Modal.jsx';

export function TimelineCenter({ onClose }) {
  const [groups, setGroups] = useState([]); const [days, setDays] = useState(14); const [offset, setOffset] = useState(0); useEffect(() => { window.deskforge.tasks.list().then(setGroups); }, []);
  const start = useMemo(() => { const date = new Date(); date.setHours(0,0,0,0); date.setDate(date.getDate() + offset); return date; }, [offset]);
  const columns = useMemo(() => Array.from({ length: days }, (_, i) => { const date = new Date(start); date.setDate(start.getDate() + i); return date; }), [start, days]);
  const tasks = groups.flatMap((group) => group.tasks.map((task) => ({ ...task, groupName: group.name }))).filter((task) => task.deadline);
  return <Modal title="项目时间线" onClose={onClose} footer={<><span className="rx-status">{start.toLocaleDateString()} 起 · {days} 天</span><button className="rx-button rx-button--ghost" onClick={onClose}>关闭</button></>}><div className="rx-timeline-tools"><button onClick={() => setOffset(offset - days)}>← 上一周期</button><button onClick={() => setOffset(0)}>今天</button><button onClick={() => setOffset(offset + days)}>下一周期 →</button><select value={days} onChange={(e) => setDays(Number(e.target.value))}><option value="14">双周视图</option><option value="30">月视图</option></select></div><div className="rx-timeline" style={{ '--days': days }}><div className="rx-timeline-corner">任务 / 日期</div>{columns.map((date) => <div className={`rx-day ${date.toDateString() === new Date().toDateString() ? 'today' : ''}`} key={date.toISOString()}><b>{date.getDate()}</b><span>{date.toLocaleDateString('zh-CN', { weekday: 'short' })}</span></div>)}{tasks.map((task) => { const deadline = new Date(`${task.deadline}T00:00:00`); const index = Math.round((deadline - start) / 86400000); return <div className="rx-timeline-row" key={task.id}><div className="rx-timeline-label"><strong>{task.name}</strong><small>{task.groupName}</small></div><div className="rx-timeline-track">{index >= 0 && index < days && <button className={`rx-milestone ${task.status === 'done' ? 'done' : ''}`} style={{ left: `calc(${index} * ((100% - 130px) / ${days}) + 130px)` }} title={`${task.id} · ${task.deadline}`}><span>{task.id}</span></button>}</div></div>})}{!tasks.length && <div className="rx-empty">为任务设置截止日期后，将在这里生成时间线</div>}</div></Modal>;
}
